name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pipenv

      - name: Install project dependencies
        run: pipenv install
        working-directory: starter/backend

      - name: Run linter
        run: pipenv run lint
        working-directory: starter/backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pipenv

      - name: Install project dependencies
        run: pipenv install
        working-directory: starter/backend

      - name: Run tests
        run: pipenv run test
        working-directory: starter/backend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ needs.lint.result == 'success' && needs.test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --tag mp-backend:latest .
        working-directory: starter/backend

      - name: Run Docker container
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend
        working-directory: starter/backend

      - name: Test running application
        run: curl http://localhost:5000/movies

      - name: Stop Docker container
        run: docker stop mp-backend
